name: Continuous Integration

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Install the JSON Schema CLI
              uses: sourcemeta/jsonschema@v11.5.1

            - name: Validate Service Schema
              run: jsonschema validate ./schema.json ./services/*.json
